import type { ReactNode } from "react";

export type LegalPageId = "terms" | "privacy" | "risk-disclosure" | "market-rules" | "support";
export type LegalSection = { id: string; title: string; content: ReactNode };
export type LegalDocument = { label: string; title: string; summary: string; draft?: boolean; sections: LegalSection[] };

const REPO = "https://github.com/penguinpecker/zedge";
const ExternalLink = ({ href, children }: { href: string; children: ReactNode }) => <a href={href} target="_blank" rel="noreferrer">{children}<span className="sr-only"> (opens in a new tab)</span></a>;

export const legalDocuments: Record<LegalPageId, LegalDocument> = {
  terms: {
    label: "Terms of service",
    title: "Terms of Service",
    summary: "Terms for using the ZEDGE preview.",
    draft: true,
    sections: [
      { id: "preview", title: "What this preview provides", content: <><p>ZEDGE is a preview of a prediction-market interface for Bitcoin and Ethereum rounds. Real-money trading has not launched. The demo uses simulated prices, liquidity, orders, fills and funds. Demo credits have no cash value and cannot be purchased, transferred or redeemed for money.</p><p>The separate chain interface can read public network data and connect to a browser wallet. Trading, deposits and withdrawals remain unavailable. A connected wallet or displayed network does not mean that an exchange is operating.</p></> },
      { id: "eligibility", title: "Who the preview is for", content: <><p>The preview is intended for adults aged 18 or older. Use it only where doing so is lawful and where you can make your own decisions about the software and services you use. Access to this website is not a statement that any future trading service is available or permitted in your location.</p><p>These draft terms apply to the current preview description. A real-money service would require its own finalized operator information, eligibility rules and terms before access is offered.</p></> },
      { id: "responsible-use", title: "Responsible use", content: <><p>Do not use the preview to impersonate another person, distribute malware, obtain someone else’s data, bypass access controls or disrupt the service. Do not present simulated performance as verified real trading results.</p><p>Report suspected vulnerabilities through the <ExternalLink href={`${REPO}/security/advisories/new`}>private security reporting channel</ExternalLink>. Use test data and assets. Do not test against another user’s account or disclose exploitable details in public issues.</p></> },
      { id: "wallet", title: "Your wallet and device", content: <><p>You control which accounts your wallet shares with the site and which network requests you approve. Review every wallet prompt. ZEDGE does not need your seed phrase or private key, and you should never send either to a maintainer.</p><p>Demo data is stored in your browser and may disappear when you clear site data, change browsers or reset the demo. It is not a backed-up financial account.</p></> },
      { id: "information", title: "Information and availability", content: <><p>Charts, examples and probabilities are for understanding the interface. They are not investment, legal or tax advice, a recommendation to transact, or a promise of future results.</p><p>The preview may contain errors or change without notice. Access, wallet connectivity and third-party network data may be delayed or unavailable. No uptime, execution or recovery guarantee is offered for this preview.</p></> },
      { id: "changes", title: "Changes and questions", content: <><p>The date on this page identifies this draft. Material changes to how the preview works should be reflected here and in the privacy notice. No operator entity, governing jurisdiction, arbitration agreement or regulatory approval is represented by this draft.</p><p>For non-sensitive questions, use the <ExternalLink href={`${REPO}/issues`}>project issue tracker</ExternalLink>. Do not include personal financial information or wallet secrets.</p></> },
    ],
  },
  privacy: {
    label: "Privacy policy",
    title: "Privacy Policy",
    summary: "What stays in your browser, what reaches other services, and what remains public.",
    draft: true,
    sections: [
      { id: "scope", title: "The current preview", content: <><p>This notice describes the current ZEDGE application. It does not claim that browsing, wallet activity or trading is anonymous. Confidential trading is under development and is not running in this preview.</p><p>The application has a local paper-trading demo and a separate interface for public blockchain reads. Neither currently accepts real trading funds.</p></> },
      { id: "local-data", title: "Your demo account", content: <><p>The demo saves its virtual balance, positions, orders, history, watchlist and simulation settings in this browser’s local storage. It uses the existing <code>edge-paper-exchange-v1</code> storage entry to preserve older demo accounts. The demo does not send that account state to a ZEDGE account server.</p><p>This storage persists until it is reset, removed by your browser or cleared in your site-data settings. Resetting the demo replaces it with a new sample account. A CSV export is downloaded to your device; you decide whether to share it.</p></> },
      { id: "wallet-network", title: "Wallet and network requests", content: <><p>After you choose to connect, the chain interface receives the selected public wallet address and network from your browser wallet. It keeps the current session in page memory. Your wallet may separately remember its site permissions; disconnecting in ZEDGE does not revoke those permissions in the wallet.</p><p>The chain interface contacts the selected Horizen network’s RPC service, including while no wallet is connected. Requests read network and block data and, where available, contract information. A balance lookup sends the selected wallet address; a transaction lookup sends the hash you enter. The service can receive your IP address and request metadata. Wallet and RPC providers operate under their own policies.</p></> },
      { id: "hosting", title: "Website hosting and support", content: <><p>The website’s hosting provider receives ordinary web requests, which can include IP address, browser information, requested paths and request times. Provider logging and retention are governed by that service’s configuration and policies; the application does not control all provider records. See <ExternalLink href="https://vercel.com/legal/privacy-notice">Vercel’s privacy notice</ExternalLink>.</p><p>Fonts are served with the application. This preview’s application code does not include an advertising or analytics SDK. That does not mean hosting or external services receive no information.</p><p>If you contact the project through GitHub, GitHub and the maintainers receive what you submit. Ordinary issues are public. Use the private security channel for vulnerability reports, and review <ExternalLink href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub’s privacy statement</ExternalLink>.</p></> },
      { id: "public-chain", title: "Public blockchain information", content: <><p>Public addresses, transactions, funding activity and withdrawal activity can reveal or connect information about a person. Blockchain records are not erased by disconnecting a wallet, clearing browser data or removing a page from this site.</p><p>Planned encrypted order and account features would protect selected contents, subject to their actual implementation. They would not automatically hide public metadata, counterparties’ knowledge, network traffic or information you choose to publish.</p></> },
      { id: "your-controls", title: "Your controls", content: <><ul><li>Use browser site-data settings to remove the local demo account, and delete exported files separately.</li><li>Use your wallet’s connected-sites settings to revoke its permission for this site.</li><li>Avoid posting wallet addresses, account screenshots or transaction details publicly when they could identify you.</li><li>Send only the information needed to explain a support issue. Never send a seed phrase, private key or sensitive unredacted log.</li></ul><p>Questions about this preview’s data handling can be raised without personal details in the <ExternalLink href={`${REPO}/issues`}>issue tracker</ExternalLink>. This draft does not establish an operator-specific privacy request process or retention schedule for a future real-money service.</p></> },
    ],
  },
  "risk-disclosure": {
    label: "Risk disclosure",
    title: "Risk Disclosure",
    summary: "Prediction outcomes, execution, wallets and privacy: the risks to understand before trading.",
    sections: [
      { id: "demo", title: "Demo results are simulated", content: <><p>The current demo uses virtual funds and synthetic market activity. It does not demonstrate available liquidity, achievable returns, real execution quality or the behavior of other traders. Its prices and fills must not be used as a real-money trading signal.</p><p>The chain interface currently supports public reads and wallet connection only. Real-money orders, deposits and withdrawals are unavailable.</p></> },
      { id: "outcomes", title: "An outcome can pay zero", content: <><p>A binary share pays according to the round’s final result. Under ZEDGE’s specified payoff, a winning share pays one collateral unit and a losing share pays zero. A voided round pays half a collateral unit per Up share and half per Down share. Anyone can block price delivery for the few minutes before a round’s closing price timeout at a small cost in network fees, so a trader holding the losing side can force a void, and winning shares then pay half a unit instead of one.</p><p>If real trading is introduced, a losing prediction could lose its entire purchase cost. Fees reduce returns. Selling before settlement would depend on an available counterparty; a displayed quote would not guarantee a fill.</p></> },
      { id: "price-time", title: "Price, timing and resolution", content: <><p>Five-minute and fifteen-minute markets are sensitive to small price changes and exact observation times. A chart’s latest price is not necessarily the observation used for resolution. Feed delays, network interruptions, disputed data and missed deadlines can affect when a result becomes final or whether a round is voided.</p><p>Read the selected round’s price source, opening and closing boundaries, trading cutoff and failure rules. A countdown is an interface aid, not proof that an order was accepted before the cutoff.</p></> },
      { id: "wallet-chain", title: "Wallets and blockchain services", content: <><p>Wallet prompts, malicious websites, compromised devices and incorrect destination addresses can put assets at risk. Blockchain transactions can be irreversible; a request can fail, remain pending or be affected by a chain reorganization. Native network fees are separate from any future trading fee.</p><p>Testnet tokens are for testing and do not demonstrate the value or safety of a mainnet asset. Do not send assets to addresses found in examples or assume a network label identifies an approved deposit address.</p></> },
      { id: "privacy-software", title: "Privacy and software limits", content: <><p>Encryption and execution inside a trusted execution environment do not eliminate software defects, key compromise, operator dependencies, hardware assumptions or information leaked by public outputs. Public order changes may allow others to infer trades even when fill records are encrypted.</p><p>The confidential exchange implementation has not completed an independent production security audit. The preview does not promise anonymity, uninterrupted service, instant settlement or recovery of lost keys or assets.</p></> },
    ],
  },
  "market-rules": {
    label: "Market rules",
    title: "Market Rules",
    summary: "Settlement, trading cutoffs and payouts for Bitcoin and Ethereum rounds.",
    sections: [
      { id: "markets", title: "Bitcoin and Ethereum rounds", content: <><p>The round contracts support BTC and ETH rounds lasting five or fifteen minutes; BTC fifteen-minute rounds are offered first. Each round has a unique identity and UTC opening and closing times. Shares in one round do not carry into the next.</p><p>The live chain interface currently cannot accept orders. The rules below describe the implemented exchange design; the paper demo’s separate simulation details appear at the end of this page.</p><p>The round registry that records these rounds is an upgradeable contract. Its owner address can replace the registry’s code, which could change these rules, including for rounds that already exist. The three contracts that verify prices and deliver them to the registry’s network are fixed. They rely on Chainlink’s verifier and the networks’ bridge contracts, which the operators of those contracts can change.</p></> },
      { id: "payoff", title: "Up, Down and a tie", content: <><p>Compare the accepted closing observation with the accepted opening observation for that exact round. A tie counts as Up.</p><div className="legal-table-wrap"><table className="legal-payoff-table"><caption>Payout for each whole outcome share</caption><thead><tr><th scope="col">Final result</th><th scope="col">Up share</th><th scope="col">Down share</th></tr></thead><tbody><tr><th scope="row">Close ≥ open</th><td>1 unit</td><td>0 units</td></tr><tr><th scope="row">Close &lt; open</th><td>0 units</td><td>1 unit</td></tr><tr><th scope="row">Round voided</th><td>0.5 units</td><td>0.5 units</td></tr></tbody></table></div><p>A unit means one unit of the round’s specified collateral, not a guaranteed fiat-dollar value. The demo represents its virtual unit as $1. A void pays half per share; it does not refund the price each trader paid.</p></> },
      { id: "observations", title: "Opening and closing observations", content: <><p>The exchange design uses the first unique, verified observation from the specified feed within each round’s boundary window. Opening and closing values must use the same price scale and the round’s stated source. The latest chart tick does not decide the outcome.</p><p>Each round fixes its observation window and a deadline for recording its opening price. If no opening price is recorded by that deadline, the round can be voided. There is no deadline for the closing price: after a round ends, it can be resolved whenever its closing price has been delivered.</p><p>An opened round can be voided only after a timeout of five minutes from the end of its closing observation window, and only while no closing price has been delivered. A void pays half a unit per Up share and half per Down share. Because this timeout is short, anyone can block price delivery for those few minutes at a small cost in network fees (about 0.03–0.05 ETH at October 2026 fees), which voids every opened round that closes at that time. A trader holding the losing side can therefore force a void, and winning shares then pay half a unit instead of one. A missing observation does not permit choosing a convenient price from another source.</p></> },
      { id: "orders", title: "Orders, fills and cancellation", content: <><p>Up and Down have separate buy and sell books. The exchange design matches funded orders by price, then accepted order sequence, at the resting order’s price. An order may fill partially. A price-protected immediate-or-cancel order cancels any unfilled remainder; a resting limit order can remain until filled, cancelled or expired.</p><p>Cash or shares needed for an order are reserved. Cancelling releases only its unfilled remainder. An already accepted fill is not undone by a later cancellation. Matching stops at the round’s cutoff, which is before its end. No leverage or uncovered sale is included in these rules.</p></> },
      { id: "collateral-fees", title: "Collateral and fees", content: <><p>In the exchange design, one unit of locked collateral creates a complete set: one Up share and one Down share. An available complete set can be merged at any time to release its collateral. After resolution, shares are redeemed according to the table above.</p><p>A trading interface must show the applicable fee and worst permitted execution price before authorization. Platform and network fees are separate. The development engine’s fee schedule is fixed for its deployment; no live trading fee is being charged by this preview.</p></> },
      { id: "demo-rules", title: "What the paper demo simulates", content: <><p>The paper demo uses a deterministic simulated price, not an external oracle. It closes orders five seconds before the round ends and finalizes its simulated result three seconds after the end. Up wins at or above the opening price; Down wins below it.</p><p>The demo applies a 1% simulated fee, rounded up to whole cents per fill, and rounds payouts down to whole cents. Its fills are whole-order simulations with no real counterparty or partial-fill model. It does not simulate oracle outages or the timeout-void process. Changing playback speed or finishing a round changes only that local simulation.</p></> },
    ],
  },
  support: {
    label: "Help & support",
    title: "Support",
    summary: "Find your way around the preview, report a problem, or share feedback with the project.",
    sections: [
      { id: "availability", title: "Why can’t I place a live order?", content: <><p>The chain interface can connect a wallet and read public network data, but the confidential trading service is not connected. Orders, deposits and withdrawals remain unavailable. Switching networks or connecting a wallet does not unlock trading.</p><p>Use the paper demo to explore the trade ticket, positions and round lifecycle with virtual funds. It is separate from your wallet and cannot move assets.</p></> },
      { id: "wallet-help", title: "Connecting a wallet", content: <><p>Use a supported browser wallet and choose Connect wallet in the chain interface. Approve only the account and network you intend to share. If the wallet changes accounts or networks, confirm that the interface shows the expected selection before continuing.</p><p>If a network read fails, check your connection and retry. A network outage does not mean your wallet balance is zero. To remove site permissions, disconnect in ZEDGE and then use the wallet’s own connected-sites settings.</p></> },
      { id: "demo-help", title: "Your demo balance and history", content: <><p>A new demo account starts with $1,000 in virtual value, including two sample positions. Demo funds cannot be withdrawn. Order reservations and open positions can make the available cash lower than the account’s total value.</p><p>The account is saved only in this browser. Resetting the demo, clearing site data or moving to another browser can replace or remove that history. Export a CSV first if you want to keep a copy.</p></> },
      { id: "report-problem", title: "Report a problem or suggest a feature", content: <><p>Use the <ExternalLink href={`${REPO}/issues`}>ZEDGE issue tracker</ExternalLink> for non-sensitive bugs and feedback. Include the page, demo or chain mode, browser, steps to reproduce, and what you expected to happen. A screenshot with personal details removed can help.</p><p>Issues are public. Do not post wallet secrets, personal financial information or unredacted logs. There is no promised support response time for this preview.</p><p><ExternalLink href={`${REPO}/issues/new`}>Open a public issue</ExternalLink></p></> },
      { id: "security-report", title: "Report a security concern privately", content: <><p>Use GitHub’s private vulnerability reporting channel for a suspected security defect. Include the affected version or commit and a minimal reproduction using test data and test assets. The project’s <ExternalLink href={`${REPO}/blob/feat/production-core/SECURITY.md`}>security policy</ExternalLink> explains the reporting boundary.</p><p>Never send a seed phrase or private key. Do not publish exploit details or test another person’s funds or account.</p><p><ExternalLink href={`${REPO}/security/advisories/new`}>Report a vulnerability privately</ExternalLink></p></> },
    ],
  },
};

export const legalNavigation: LegalPageId[] = ["terms", "privacy", "risk-disclosure", "market-rules", "support"];
