import type { ReactNode } from "react";

export type LegalPageId = "terms" | "privacy" | "risk-disclosure" | "market-rules" | "support";
export type LegalSection = { id: string; title: string; content: ReactNode };
export type LegalDocument = { label: string; title: string; summary: string; draft?: boolean; sections: LegalSection[] };

const REPO = "https://github.com/penguinpecker/zedge";
const ExternalLink = ({ href, children }: { href: string; children: ReactNode }) => <a href={href} target="_blank" rel="noreferrer">{children}<span className="sr-only"> (opens in a new tab)</span></a>;

export const legalDocuments: Record<LegalPageId, LegalDocument> = {
  terms: {
    label: "Terms of service",
    title: "Terms of Service",
    summary: "Terms for using ZEDGE.",
    draft: true,
    sections: [
      { id: "service", title: "What ZEDGE provides", content: <><p>ZEDGE runs a private order book for Bitcoin 15-minute Up/Down rounds. You deposit native USDC on Base into the ZEDGE vault, trade from a private balance, and withdraw to your address on Base. Each round settles on Chainlink’s BTC/USD price. Your orders and trading balance are hidden from the public but visible to the ZEDGE operator.</p><p>A separate paper demo uses simulated prices, liquidity, orders, fills and funds. Demo credits have no cash value and cannot be purchased, transferred or redeemed for money.</p></> },
      { id: "eligibility", title: "Who ZEDGE is for", content: <><p>ZEDGE is intended for adults aged 18 or older. Use it only where doing so is lawful and where you can make your own decisions about the software and services you use. Access to this website is not a statement that trading is permitted in your location.</p><p>These are draft terms for the service as it runs today. They are not final and may change.</p></> },
      { id: "responsible-use", title: "Responsible use", content: <><p>Do not use ZEDGE to impersonate another person, distribute malware, obtain someone else’s data, bypass access controls or disrupt the service. Do not present simulated performance as verified real trading results.</p><p>Report suspected vulnerabilities through the <ExternalLink href={`${REPO}/security/advisories/new`}>private security reporting channel</ExternalLink>. Use test data and assets. Do not test against another user’s account or disclose exploitable details in public issues.</p></> },
      { id: "wallet", title: "Your wallet and device", content: <><p>Signing in with Google or X creates a wallet for you through Privy. The site uses it to sign your deposits, orders and withdrawals in the background, without a prompt for each one. Anyone who takes over your Google or X account can sign in as you and reach your funds, so protect those accounts. ZEDGE does not need your seed phrase or private key, and you should never send either to a maintainer.</p><p>Demo data is stored in your browser and may disappear when you clear site data, change browsers or reset the demo. It is not a backed-up financial account.</p></> },
      { id: "information", title: "Information and availability", content: <><p>Charts, examples and probabilities are for understanding the interface. They are not investment, legal or tax advice, a recommendation to transact, or a promise of future results.</p><p>ZEDGE may contain errors or change without notice. Trading, deposits, settlement, withdrawals and third-party network data may be delayed or unavailable. No uptime, execution or recovery guarantee is offered.</p></> },
      { id: "changes", title: "Changes and questions", content: <><p>The date on this page identifies this draft. Material changes to how ZEDGE works should be reflected here and in the privacy notice. No operator entity, governing jurisdiction, arbitration agreement or regulatory approval is represented by this draft.</p><p>For non-sensitive questions, use the <ExternalLink href={`${REPO}/issues`}>project issue tracker</ExternalLink>. Do not include personal financial information or wallet secrets.</p></> },
    ],
  },
  privacy: {
    label: "Privacy policy",
    title: "Privacy Policy",
    summary: "What stays in your browser, what reaches other services, and what remains public.",
    draft: true,
    sections: [
      { id: "scope", title: "What this notice covers", content: <><p>This notice describes the current ZEDGE application. It does not claim that browsing, wallet activity or trading is anonymous.</p><p>The application has a live market, where you trade real USDC from a private balance, and a separate local paper-trading demo that holds no real funds.</p></> },
      { id: "local-data", title: "Your demo account", content: <><p>The demo saves its virtual balance, positions, orders, history, watchlist and simulation settings in this browser’s local storage. It uses the existing <code>edge-paper-exchange-v1</code> storage entry to preserve older demo accounts. The demo does not send that account state to a ZEDGE account server.</p><p>This storage persists until it is reset, removed by your browser or cleared in your site-data settings. Resetting the demo replaces it with a new sample account. A CSV export is downloaded to your device; you decide whether to share it.</p></> },
      { id: "wallet-network", title: "Wallet and network requests", content: <><p>You sign in with Google or X through Privy. Privy receives the account details Google or X share with it and creates a wallet for you; that wallet’s address is your deposit address on Base. Privy keeps your sign-in session in this browser and handles your data under its own policy. The live market also stores a fingerprint of your trading key in this browser, not the key itself.</p><p>When you deposit, trade or withdraw, ZEDGE’s relayer receives your sign-in token and your signed request and submits it on chain for you. It logs each request’s type, your wallet address and any deposit amount, and keeps rate-limit counters tied to your Privy user ID for up to two days.</p><p>The live market reads Horizen and Base through RPC services, including while you are signed out. While you are signed in, reads include your wallet address, to show your balance and your requests. A transaction lookup sends the hash you enter. These services can receive your IP address and request metadata and operate under their own policies.</p></> },
      { id: "operator", title: "What the operator sees", content: <><p>Your orders, balance, positions and fills are encrypted before they reach the public chain, so other users and chain observers cannot read them. The ZEDGE operator runs the order book engine and can read all of them for every account.</p></> },
      { id: "hosting", title: "Website hosting and support", content: <><p>The website’s hosting provider receives ordinary web requests, which can include IP address, browser information, requested paths and request times. Provider logging and retention are governed by that service’s configuration and policies; the application does not control all provider records. See <ExternalLink href="https://vercel.com/legal/privacy-notice">Vercel’s privacy notice</ExternalLink>.</p><p>Fonts are served with the application. The application code does not include an advertising SDK. The chain interface includes Privy’s sign-in SDK, which reports usage events to Privy, such as each time your Privy wallet signs, under Privy’s own policy. Hosting and external services can also receive information.</p><p>If you contact the project through GitHub, GitHub and the maintainers receive what you submit. Ordinary issues are public. Use the private security channel for vulnerability reports, and review <ExternalLink href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub’s privacy statement</ExternalLink>.</p></> },
      { id: "public-chain", title: "Public blockchain information", content: <><p>Public addresses, transactions, funding activity and withdrawal activity can reveal or connect information about a person. Blockchain records are not erased by disconnecting a wallet, clearing browser data or removing a page from this site.</p><p>Chain observers can see deposits and withdrawals on Base with their amounts and addresses, which addresses send requests to the order book and when, and each round’s prices and result. Encryption does not hide that metadata, network traffic or information you choose to publish.</p></> },
      { id: "your-controls", title: "Your controls", content: <><ul><li>Use browser site-data settings to remove the local demo account, and delete exported files separately.</li><li>Sign out to end your session on this device.</li><li>Avoid posting wallet addresses, account screenshots or transaction details publicly when they could identify you.</li><li>Send only the information needed to explain a support issue. Never send a seed phrase, private key or sensitive unredacted log.</li></ul><p>Questions about ZEDGE’s data handling can be raised without personal details in the <ExternalLink href={`${REPO}/issues`}>issue tracker</ExternalLink>. This draft does not yet set out a privacy request process or retention schedule.</p></> },
    ],
  },
  "risk-disclosure": {
    label: "Risk disclosure",
    title: "Risk Disclosure",
    summary: "Prediction outcomes, execution, wallets and privacy: the risks to understand before trading.",
    sections: [
      { id: "demo", title: "Demo results are simulated", content: <><p>The current demo uses virtual funds and synthetic market activity. It does not demonstrate available liquidity, achievable returns, real execution quality or the behavior of other traders. Its prices and fills must not be used as a real-money trading signal.</p><p>The live market trades real USDC. The demo is separate and cannot move funds.</p></> },
      { id: "outcomes", title: "An outcome can pay zero", content: <><p>A binary share pays according to the round’s final result. Under ZEDGE’s specified payoff, a winning share pays one collateral unit and a losing share pays zero. A voided round pays half a collateral unit per Up share and half per Down share. Anyone can block price delivery for the few minutes before a round’s closing price timeout at a small cost in network fees, so a trader holding the losing side can force a void, and winning shares then pay half a unit instead of one.</p><p>A losing prediction loses its entire purchase cost. The live order book charges no trading fee. Selling before settlement depends on an available counterparty; a displayed quote does not guarantee a fill.</p></> },
      { id: "price-time", title: "Price, timing and resolution", content: <><p>Five-minute and fifteen-minute markets are sensitive to small price changes and exact observation times. A chart’s latest price is not necessarily the observation used for resolution. Feed delays, network interruptions, disputed data and missed deadlines can affect when a result becomes final or whether a round is voided.</p><p>Read the selected round’s price source, opening and closing boundaries, trading cutoff and failure rules. A countdown is an interface aid, not proof that an order was accepted before the cutoff.</p></> },
      { id: "wallet-chain", title: "Wallets and blockchain services", content: <><p>Anyone who takes over your Google or X account, or your device while you are signed in, can trade and withdraw as you. Malicious websites and incorrect destination addresses can also put assets at risk. Blockchain transactions can be irreversible; a request can fail, remain pending or be affected by a chain reorganization. ZEDGE pays the network fees for deposits into the vault, orders and withdrawals.</p><p>Send only native USDC on Base to your deposit address. Other tokens, and USDC sent on another network, are not credited. Do not send assets to addresses found in examples or assume a network label identifies an approved deposit address.</p></> },
      { id: "privacy-software", title: "Privacy and software limits", content: <><p>Orders are encrypted on the public chain, but the operator runs the engine and can read every order, balance and position. The engine does not run on attested hardware, so nothing proves to you which code processed your orders. Public order changes may allow others to infer trades even when fill records are encrypted.</p><p>ZEDGE’s contracts and engine have not had an independent security audit. ZEDGE does not promise anonymity, uninterrupted service, instant settlement or recovery of lost keys or assets.</p></> },
      { id: "operator", title: "Operator, relayer and contracts", content: <><p>You rely on the operator. It runs the order book engine, signs every withdrawal and owns the vault contract on Base. Nothing in the software stops the operator from misusing that access. The operator also trades as the house and is often the other side of your trade.</p><p>If the engine, the relayer, the price service or the Horizen or Base networks stop, orders, settlement, deposits and withdrawals stop until they recover. If the engine’s data were lost, private balances might not be recoverable. The vault pays at most 1,000 USDC per withdrawal and 10,000 USDC a day in total, so a withdrawal can wait.</p><p>A defect in the contracts or the engine can lose or lock funds. The vault, the deposit inbox and the round registry are upgradeable: their owner can replace their code.</p></> },
    ],
  },
  "market-rules": {
    label: "Market rules",
    title: "Market Rules",
    summary: "Settlement, trading cutoffs and payouts for Bitcoin and Ethereum rounds.",
    sections: [
      { id: "markets", title: "Bitcoin and Ethereum rounds", content: <><p>The round contracts support BTC and ETH rounds lasting five or fifteen minutes; BTC fifteen-minute rounds are offered first. Each round has a unique identity and UTC opening and closing times. Shares in one round do not carry into the next.</p><p>The live order book offers BTC fifteen-minute rounds and settles them by the rules below. Its engine checks Chainlink’s signatures on the BTC/USD report for each round’s exact opening and closing second; if that report does not arrive, it uses the round registry’s record instead. The paper demo’s separate simulation details appear at the end of this page.</p><p>The round registry that records these rounds is an upgradeable contract. Its owner address can replace the registry’s code, which could change these rules, including for rounds that already exist. The three contracts that verify prices and deliver them to the registry’s network are fixed. They rely on Chainlink’s verifier and the networks’ bridge contracts, which the operators of those contracts can change.</p></> },
      { id: "payoff", title: "Up, Down and a tie", content: <><p>Compare the accepted closing observation with the accepted opening observation for that exact round. A tie counts as Up.</p><div className="legal-table-wrap"><table className="legal-payoff-table"><caption>Payout for each whole outcome share</caption><thead><tr><th scope="col">Final result</th><th scope="col">Up share</th><th scope="col">Down share</th></tr></thead><tbody><tr><th scope="row">Close ≥ open</th><td>1 unit</td><td>0 units</td></tr><tr><th scope="row">Close &lt; open</th><td>0 units</td><td>1 unit</td></tr><tr><th scope="row">Round voided</th><td>0.5 units</td><td>0.5 units</td></tr></tbody></table></div><p>A unit means one unit of the round’s specified collateral, not a guaranteed fiat-dollar value. The demo represents its virtual unit as $1. A void pays half per share; it does not refund the price each trader paid.</p></> },
      { id: "observations", title: "Opening and closing observations", content: <><p>The exchange design uses the first unique, verified observation from the specified feed within each round’s boundary window. Opening and closing values must use the same price scale and the round’s stated source. The latest chart tick does not decide the outcome.</p><p>Each round fixes its observation window and a deadline for recording its opening price. If no opening price is recorded by that deadline, the round can be voided. There is no deadline for the closing price: after a round ends, it can be resolved whenever its closing price has been delivered.</p><p>An opened round can be voided only after a timeout of five minutes from the end of its closing observation window, and only while no closing price has been delivered. A void pays half a unit per Up share and half per Down share. Because this timeout is short, anyone can block price delivery for those few minutes at a small cost in network fees (about 0.03–0.05 ETH at October 2026 fees), which voids every opened round that closes at that time. A trader holding the losing side can therefore force a void, and winning shares then pay half a unit instead of one. A missing observation does not permit choosing a convenient price from another source.</p></> },
      { id: "orders", title: "Orders, fills and cancellation", content: <><p>Up and Down have separate buy and sell books. The exchange design matches funded orders by price, then accepted order sequence, at the resting order’s price. An order may fill partially. A price-protected immediate-or-cancel order cancels any unfilled remainder; a resting limit order can remain until filled, cancelled or expired.</p><p>Cash or shares needed for an order are reserved. Cancelling releases only its unfilled remainder. An already accepted fill is not undone by a later cancellation. Matching stops at the round’s cutoff, which is before its end. No leverage or uncovered sale is included in these rules.</p></> },
      { id: "collateral-fees", title: "Collateral and fees", content: <><p>In the exchange design, one unit of locked collateral creates a complete set: one Up share and one Down share. An available complete set can be merged at any time to release its collateral. After resolution, shares are redeemed according to the table above.</p><p>A trading interface must show the applicable fee and worst permitted execution price before authorization. Platform and network fees are separate. The engine’s fee schedule is fixed for its deployment. The live order book charges no trading fee, and ZEDGE pays the network fees for deposits into the vault, orders and withdrawals.</p></> },
      { id: "demo-rules", title: "What the paper demo simulates", content: <><p>The paper demo uses a deterministic simulated price, not an external oracle. It closes orders five seconds before the round ends and finalizes its simulated result three seconds after the end. Up wins at or above the opening price; Down wins below it.</p><p>The demo applies a 1% simulated fee, rounded up to whole cents per fill, and rounds payouts down to whole cents. Its fills are whole-order simulations with no real counterparty or partial-fill model. It does not simulate oracle outages or the timeout-void process. Changing playback speed or finishing a round changes only that local simulation.</p></> },
    ],
  },
  support: {
    label: "Help & support",
    title: "Support",
    summary: "Find your way around ZEDGE, report a problem, or share feedback with the project.",
    sections: [
      { id: "live-market", title: "Deposit, trade and withdraw", content: <><p>Send native USDC on Base to the deposit address in your wallet popup, then choose Deposit. Each deposit is 1 to 500 USDC and goes into the ZEDGE vault. The popup shows three steps: Sent on Base, Reached Horizen, Credited. Credit usually takes about a minute.</p><p>Pick Up or Down and an amount to buy from your trading balance. Any part of an order that cannot fill at your price is cancelled. When a round settles, each winning share pays 1 USDC into your trading balance.</p><p>Withdraw sends your trading balance, up to 1,000 USDC at a time, to your address on Base. Once your USDC is at your deposit address, ZEDGE pays the network fees for depositing, trading and withdrawing.</p><p>The paper demo is separate. It uses virtual funds and cannot move assets.</p></> },
      { id: "wallet-help", title: "Signing in and your wallet", content: <><p>Sign in with Google or X. Signing in creates a wallet for you; there is no browser-wallet option. Its address is your deposit address, and withdrawals are paid to it on Base. Sign out to end the session on this device.</p><p>If a network read fails, check your connection and retry. A network outage does not mean your balance is zero.</p></> },
      { id: "demo-help", title: "Your demo balance and history", content: <><p>A new demo account starts with $1,000 in virtual value, including two sample positions. Demo funds cannot be withdrawn. Order reservations and open positions can make the available cash lower than the account’s total value.</p><p>The account is saved only in this browser. Resetting the demo, clearing site data or moving to another browser can replace or remove that history. Export a CSV first if you want to keep a copy.</p></> },
      { id: "report-problem", title: "Report a problem or suggest a feature", content: <><p>Use the <ExternalLink href={`${REPO}/issues`}>ZEDGE issue tracker</ExternalLink> for non-sensitive bugs and feedback. Include the page, demo or chain mode, browser, steps to reproduce, and what you expected to happen. A screenshot with personal details removed can help.</p><p>Issues are public. Do not post wallet secrets, personal financial information or unredacted logs. There is no promised support response time.</p><p><ExternalLink href={`${REPO}/issues/new`}>Open a public issue</ExternalLink></p></> },
      { id: "security-report", title: "Report a security concern privately", content: <><p>Use GitHub’s private vulnerability reporting channel for a suspected security defect. Include the affected version or commit and a minimal reproduction using test data and test assets. The project’s <ExternalLink href={`${REPO}/blob/feat/production-core/SECURITY.md`}>security policy</ExternalLink> explains the reporting boundary.</p><p>Never send a seed phrase or private key. Do not publish exploit details or test another person’s funds or account.</p><p><ExternalLink href={`${REPO}/security/advisories/new`}>Report a vulnerability privately</ExternalLink></p></> },
    ],
  },
};

export const legalNavigation: LegalPageId[] = ["terms", "privacy", "risk-disclosure", "market-rules", "support"];
