[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib", "node_modules"]
solc = "0.8.30"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
remappings = ["@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/", "@pythnetwork/pyth-sdk-solidity/=node_modules/@pythnetwork/pyth-sdk-solidity/", "forge-std/=lib/forge-std/src/"]

[profile.default.fuzz]
runs = 1024

[profile.default.invariant]
runs = 256
depth = 128
fail_on_revert = true

[fmt]
line_length = 110

[profile.ci.fuzz]
runs = 4096

[profile.ci.invariant]
runs = 512
depth = 256
fail_on_revert = true
