package guest

import (
	"bytes"
	"encoding/json"
	"flag"
	"os"
	"strings"
	"testing"

	"github.com/penguinpecker/zedge/engine"
)

var update = flag.Bool("update", false, "rewrite testdata/vectors.json")

// testdata/vectors.json is the contract with adapters/vela/crypto: guest.test.ts
// requires its encoder to produce every "canonical" string, session.ts to
// produce every request "plaintext", and every receipt "plaintext" to pass the
// session's context checks. This test requires the same file to be exactly
// what the engine and this adapter produce and accept.
//
//	go test -run TestVectors -update .
type commandVector struct {
	Name      string          `json:"name"`
	Command   json.RawMessage `json:"command"` // the same command with its keys sorted and zero fields spelled out
	Canonical string          `json:"canonical"`
}
type requestVector struct {
	Name      string      `json:"name"`
	Account   string      `json:"account"`
	RequestID string      `json:"requestId"`
	Body      requestBody `json:"body"`
	Plaintext string      `json:"plaintext"`
}
type receiptVector struct {
	Name      string `json:"name"`
	Account   string `json:"account"`
	RequestID string `json:"requestId"`
	Type      string `json:"type"`
	Status    string `json:"status"`
	Plaintext string `json:"plaintext"`
}
type vectors struct {
	Note     string            `json:"note"`
	Domain   envelopeDomain    `json:"domain"`
	Epoch    string            `json:"epoch"`
	Accounts map[string]string `json:"accounts"`
	Commands []commandVector   `json:"commands"`
	Requests []requestVector   `json:"requests"`
	Receipts []receiptVector   `json:"receipts"`
}

func TestVectors(t *testing.T) {
	v := vectors{Note: "Generated by `go test -run TestVectors -update .` in adapters/vela/guest. Do not edit.", Domain: testDomain(), Epoch: epoch, Accounts: map[string]string{"alice": alice, "bob": bob}}

	spec, err := engine.NewRoundSpec(deployed(), "BTC", 900, 1_800_000_900)
	if err != nil {
		t.Fatal(err)
	}
	round := engine.RoundID(deployed(), spec)
	observation := &engine.StreamsObservation{FeedID: engine.BTCStreamsFeed, Price: "97000000000000000000000", ValidFromTimestamp: 1_800_000_800, ObservationsTimestamp: 1_800_000_901, ExpiresAt: 1_800_086_400, ReportHash: "0x" + strings.Repeat("5e", 32), Decimals: 18}
	for _, c := range []struct {
		name    string
		account string
		nonce   uint64
		command engine.Command
	}{
		{"register", alice, 1, engine.Command{Op: engine.Register}},
		{"request_withdrawal", alice, 2, engine.Command{Op: engine.RequestWithdrawal, Amount: 50_000_000, Destination: outside}},
		{"cancel_withdrawal", alice, 3, engine.Command{Op: engine.CancelWithdrawal, WithdrawalID: alice + ":2"}},
		{"mint", alice, 4, engine.Command{Op: engine.Mint, RoundID: round, Quantity: 5_000_000}},
		{"merge", alice, 5, engine.Command{Op: engine.Merge, RoundID: round, Quantity: 1_000}},
		{"place_order", alice, 6, engine.Command{Op: engine.PlaceOrder, RoundID: round, Outcome: engine.Down, Side: engine.Sell, Price: 99, Quantity: 1_000_000, TIF: engine.GTC, Expiry: spec.Cutoff, MaxFee: 9_900}},
		{"cancel_order", alice, 7, engine.Command{Op: engine.CancelOrder, OrderID: alice + ":6"}},
		{"cancel_all", alice, 8, engine.Command{Op: engine.CancelAll, RoundID: round}},
		{"redeem", alice, 9, engine.Command{Op: engine.Redeem, RoundID: round}},
		{"largest integers", bob, engine.MaxAtoms, engine.Command{Op: engine.RequestWithdrawal, Amount: engine.MaxAtoms, Destination: bob}},
		{"create_round", trigger, 1, engine.Command{Op: engine.CreateRound, Round: &spec}},
		{"open_round", trigger, 2, engine.Command{Op: engine.OpenRound, RoundID: round, Evidence: strings.Repeat("5e", 32), RegistryTime: 1_800_000_905, Observation: observation}},
		{"void_round", trigger, 3, engine.Command{Op: engine.VoidRound, RoundID: round, Evidence: round, RegistryTime: 1_801_000_000}},
	} {
		cmd := c.command
		cmd.Domain, cmd.Nonce, cmd.ID = deployed().Domain, c.nonce, engine.CommandID(c.account, c.nonce)
		if c.account != trigger {
			cmd.Account = c.account
		}
		text := marshal(cmd)
		if decoded, err := engine.DecodeCommand(text); err != nil || !bytes.Equal(marshal(decoded), text) {
			t.Fatalf("%s: engine.DecodeCommand refused its own canonical form: %v", c.name, err)
		}
		// Sorted keys, and every absent scalar spelled out as its zero value: an
		// encoder has to restore the order and drop the zeros.
		loose := map[string]any{}
		d := json.NewDecoder(bytes.NewReader(text))
		d.UseNumber()
		if err := d.Decode(&loose); err != nil {
			t.Fatal(err)
		}
		for _, k := range []string{"account", "roundId", "outcome", "side", "tif", "orderId", "withdrawalId", "destination", "evidence"} {
			if _, ok := loose[k]; !ok {
				loose[k] = ""
			}
		}
		for _, k := range []string{"amount", "price", "quantity", "expiry", "maxFee", "registryTime"} {
			if _, ok := loose[k]; !ok {
				loose[k] = 0
			}
		}
		v.Commands = append(v.Commands, commandVector{c.name, marshal(loose), string(text)})
	}

	steps := run(t, script()[:30])
	for name, title := range map[string]string{"register": "explicit register after a deposit is a retry", "withdraw": "alice withdraws", "sync": "sync asks for tick 10"} {
		s := find(t, steps, title)
		var e requestEnvelope
		if s.Error != "" || !canonical(s.Payload, &e) {
			t.Fatalf("%s: the script's own request is not canonical", title)
		}
		v.Requests = append(v.Requests, requestVector{name, e.Account, e.RequestID, e.Body, string(s.Payload)})
	}
	for _, title := range []string{"first deposit registers and credits alice", "explicit register after a deposit is a retry", "bob registers", "alice withdraws", "overdraft is rejected in private", "sync asks for tick 10", "bob deposits"} {
		for _, e := range find(t, steps, title).Events {
			r := body(t, e)
			v.Receipts = append(v.Receipts, receiptVector{title, r.Account, r.RequestID, r.Body.Type, r.Body.Status, string(e.Data)})
		}
	}
	// Map iteration order is random; the file must not be.
	for i := range v.Requests {
		for j := i + 1; j < len(v.Requests); j++ {
			if v.Requests[j].Name < v.Requests[i].Name {
				v.Requests[i], v.Requests[j] = v.Requests[j], v.Requests[i]
			}
		}
	}

	want, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	want = append(want, '\n')
	if *update {
		if err := os.WriteFile("testdata/vectors.json", want, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	got, err := os.ReadFile("testdata/vectors.json")
	if err != nil || !bytes.Equal(got, want) {
		t.Fatalf("testdata/vectors.json is stale or missing (%v): run go test -run TestVectors -update . and rerun the TypeScript tests", err)
	}
}
