package guest

import (
	"bytes"
	"encoding/hex"
	"encoding/json"
	"flag"
	"os"
	"strings"
	"testing"

	"github.com/penguinpecker/zedge/engine"
)

var update = flag.Bool("update", false, "rewrite testdata/vectors.json")

// testdata/vectors.json is the contract with adapters/vela/crypto: guest.test.ts
// requires its encoder to produce every "canonical" string, session.ts to
// produce every request "plaintext" from guest.ts's body, and every receipt
// "plaintext" to pass the session's context checks; pad.test.ts requires
// pad.ts to turn that body into the request "padded", the only form the guest
// accepts (README section 4). This test requires the same file to be exactly
// what the engine and this adapter produce and accept.
//
//	go test -run TestVectors -update .
type commandVector struct {
	Name      string          `json:"name"`
	Command   json.RawMessage `json:"command"` // the same command with its keys sorted and zero fields spelled out
	Canonical string          `json:"canonical"`
}
type requestVector struct {
	Name      string   `json:"name"`
	Account   string   `json:"account"`
	RequestID string   `json:"requestId"`
	Body      bareBody `json:"body"`      // guest.ts's body, before padding
	Plaintext string   `json:"plaintext"` // what session.ts encrypts for that body, which the guest refuses
	Padded    string   `json:"padded"`    // the same request padded by pad.ts, which the guest accepts
}

// bareBody and bareEnvelope are a request before ../crypto/pad.ts pads it.
type bareBody struct {
	Type      string `json:"type"`
	Command   string `json:"command,omitempty"`
	Report    string `json:"report,omitempty"`
	Outcome   uint64 `json:"outcome,omitempty"`
	Signature string `json:"signature,omitempty"`
}
type bareEnvelope struct {
	Version   uint32         `json:"version"`
	Domain    envelopeDomain `json:"domain"`
	Account   string         `json:"account"`
	Epoch     string         `json:"epoch"`
	RequestID string         `json:"requestId"`
	Kind      string         `json:"kind"`
	Body      bareBody       `json:"body"`
}
type receiptVector struct {
	Name      string `json:"name"`
	Account   string `json:"account"`
	RequestID string `json:"requestId"`
	Type      string `json:"type"`
	Status    string `json:"status"`
	Plaintext string `json:"plaintext"`
}

// recordVector is one public app event of the script, as the chain carries it.
type recordVector struct {
	Name    string `json:"name"`
	SubType string `json:"subType"`
	Data    string `json:"data"`
}

// eventVector is the event of the script's third deployment (README section
// 13): what guest.ts must derive from the engine configuration and the event's
// terms, the EIP-712 digest its resolver signs, and that signature.
type eventVector struct {
	EngineConfig string           `json:"engineConfig"` // canonical JSON of the deployed engine configuration
	Event        EventTerms       `json:"event"`
	Spec         engine.RoundSpec `json:"spec"`
	RoundID      string           `json:"roundId"`
	Resolver     string           `json:"resolver"`
	Outcome      uint64           `json:"outcome"`
	Digest       string           `json:"digest"`
	Signature    string           `json:"signature"`
}
type vectors struct {
	Note     string            `json:"note"`
	Domain   envelopeDomain    `json:"domain"`
	Epoch    string            `json:"epoch"`
	Accounts map[string]string `json:"accounts"`
	Commands []commandVector   `json:"commands"`
	Requests []requestVector   `json:"requests"`
	Receipts []receiptVector   `json:"receipts"`
	Records  []recordVector    `json:"records"`
	Event    eventVector       `json:"event"`
}

func TestVectors(t *testing.T) {
	v := vectors{Note: "Generated by `go test -run TestVectors -update .` in adapters/vela/guest. Do not edit.", Domain: testDomain(), Epoch: epoch, Accounts: map[string]string{"alice": alice, "bob": bob}}

	spec, err := engine.NewRoundSpec(deployed(), "BTC", 900, 1_800_000_900)
	if err != nil {
		t.Fatal(err)
	}
	round := engine.RoundID(deployed(), spec)
	event, eventRound := mustEventSpec(), eventID(testEvent())
	observation := &engine.StreamsObservation{FeedID: engine.BTCStreamsFeed, Price: "97000000000000000000000", ValidFromTimestamp: 1_800_000_800, ObservationsTimestamp: 1_800_000_901, ExpiresAt: 1_800_086_400, ReportHash: "0x" + strings.Repeat("5e", 32), Decimals: 18}
	for _, c := range []struct {
		name    string
		account string
		nonce   uint64
		command engine.Command
	}{
		{"register", alice, 1, engine.Command{Op: engine.Register}},
		{"request_withdrawal", alice, 2, engine.Command{Op: engine.RequestWithdrawal, Amount: 50_000_000, Destination: outside}},
		{"cancel_withdrawal", alice, 3, engine.Command{Op: engine.CancelWithdrawal, WithdrawalID: alice + ":2"}},
		{"mint", alice, 4, engine.Command{Op: engine.Mint, RoundID: round, Quantity: 5_000_000}},
		{"merge", alice, 5, engine.Command{Op: engine.Merge, RoundID: round, Quantity: 1_000}},
		{"place_order", alice, 6, engine.Command{Op: engine.PlaceOrder, RoundID: round, Outcome: engine.Down, Side: engine.Sell, Price: 99, Quantity: 1_000_000, TIF: engine.GTC, Expiry: spec.Cutoff, MaxFee: 9_900}},
		{"cancel_order", alice, 7, engine.Command{Op: engine.CancelOrder, OrderID: alice + ":6"}},
		{"cancel_all", alice, 8, engine.Command{Op: engine.CancelAll, RoundID: round}},
		{"redeem", alice, 9, engine.Command{Op: engine.Redeem, RoundID: round}},
		{"largest integers", bob, engine.MaxAtoms, engine.Command{Op: engine.RequestWithdrawal, Amount: engine.MaxAtoms, Destination: bob}},
		{"create_round", trigger, 1, engine.Command{Op: engine.CreateRound, Round: &spec}},
		{"open_round", trigger, 2, engine.Command{Op: engine.OpenRound, RoundID: round, Evidence: strings.Repeat("5e", 32), RegistryTime: 1_800_000_905, Observation: observation}},
		{"void_round", trigger, 3, engine.Command{Op: engine.VoidRound, RoundID: round, Evidence: round, RegistryTime: 1_801_000_000}},
		{"create_round of the event", trigger, 4, engine.Command{Op: engine.CreateRound, Round: &event}},
		{"resolve_round of the event", trigger, 5, engine.Command{Op: engine.ResolveRound, RoundID: eventRound, Outcome: engine.Down, Evidence: event.RegistryRoundID[2:], RegistryTime: testEvent().End}},
	} {
		cmd := c.command
		cmd.Domain, cmd.Nonce, cmd.ID = deployed().Domain, c.nonce, engine.CommandID(c.account, c.nonce)
		if c.account != trigger {
			cmd.Account = c.account
		}
		text := marshal(cmd)
		if decoded, err := engine.DecodeCommand(text); err != nil || !bytes.Equal(marshal(decoded), text) {
			t.Fatalf("%s: engine.DecodeCommand refused its own canonical form: %v", c.name, err)
		}
		// Sorted keys, and every absent scalar spelled out as its zero value: an
		// encoder has to restore the order and drop the zeros.
		loose := map[string]any{}
		d := json.NewDecoder(bytes.NewReader(text))
		d.UseNumber()
		if err := d.Decode(&loose); err != nil {
			t.Fatal(err)
		}
		for _, k := range []string{"account", "roundId", "outcome", "side", "tif", "orderId", "withdrawalId", "destination", "evidence"} {
			if _, ok := loose[k]; !ok {
				loose[k] = ""
			}
		}
		for _, k := range []string{"amount", "price", "quantity", "expiry", "maxFee", "registryTime"} {
			if _, ok := loose[k]; !ok {
				loose[k] = 0
			}
		}
		v.Commands = append(v.Commands, commandVector{c.name, marshal(loose), string(text)})
	}

	steps := run(t, script())
	for name, title := range map[string]string{"register": "explicit register after a deposit is a retry", "withdraw": "alice withdraws", "sync": "sync asks for tick 10",
		"report": "reports: alice's report for b1 resolves round 0, pays the winners and opens round 1", "resolve": "events: alice carries the resolver's No, which pays every holder and archives the event"} {
		s := find(t, steps, title)
		var e requestEnvelope
		if s.Error != "" || !canonical(s.Payload, &e) || len(s.Payload) != RequestBytes {
			t.Fatalf("%s: the script's own request is not canonical", title)
		}
		b := bareBody{e.Body.Type, e.Body.Command, e.Body.Report, e.Body.Outcome, e.Body.Signature}
		v.Requests = append(v.Requests, requestVector{name, e.Account, e.RequestID, b, string(marshal(bareEnvelope{e.Version, e.Domain, e.Account, e.Epoch, e.RequestID, e.Kind, b})), string(s.Payload)})
	}
	for _, title := range []string{"explicit register after a deposit is a retry", "bob registers", "alice withdraws", "overdraft is rejected in private", "sync asks for tick 10",
		"order for an unknown round is staged", "alice collects her order's outcome and stages a cancel", "bob collects his fill",
		"reports: alice's report for b1 resolves round 0, pays the winners and opens round 1", "reports: the other copy of that report is already applied",
		"events: the resolver's No before the end is refused in private", "events: alice carries the resolver's No, which pays every holder and archives the event",
		"events: the same result again has nothing to apply"} {
		for _, e := range find(t, steps, title).Events {
			r := body(t, e)
			v.Receipts = append(v.Receipts, receiptVector{title, r.Account, r.RequestID, r.Body.Type, r.Body.Status, string(e.Data)})
		}
	}
	for _, r := range []struct {
		title string
		index int
	}{
		{"tick 1 sets the clock and credits alice's first Base deposit, registering her", 0},
		{"tick 1 sets the clock and credits alice's first Base deposit, registering her", 1},
		{"alice withdraws", 0},
		{"alice withdraws", 1},
		{"tick 15 credits accounts 27 to 32 and refunds the deposit past the account limit", 7},
		{"tick 15 credits accounts 27 to 32 and refunds the deposit past the account limit", 8},
		{"reports: alice's report for b1 resolves round 0, pays the winners and opens round 1", 0},
		{"reports: alice's report for b1 resolves round 0, pays the winners and opens round 1", 1},
		{"reports: tick 8 skips a repeated deposit, credits two and confirms round 0", 3},
		{"events: alice carries the resolver's No, which pays every holder and archives the event", 0},
	} {
		e := find(t, steps, r.title).AppEvents[r.index]
		v.Records = append(v.Records, recordVector{r.title, "0x" + hex.EncodeToString(e.EventSubType[:]), "0x" + hex.EncodeToString(e.Data)})
	}
	digest := (&State{Engine: &engine.State{Config: deployed()}}).resultDigest(eventRound, 2)
	v.Event = eventVector{string(marshal(deployed())), *testEvent(), event, eventRound, resolver, 2, "0x" + hex.EncodeToString(digest), signResult(resolverKey, deployed(), eventRound, 2)}
	if signer := (&State{Engine: &engine.State{Config: deployed()}}).resultSigner(eventRound, 2, raw(v.Event.Signature)); signer != resolver {
		t.Fatalf("the vector's signature recovers to %s", signer)
	}
	// Map iteration order is random; the file must not be.
	for i := range v.Requests {
		for j := i + 1; j < len(v.Requests); j++ {
			if v.Requests[j].Name < v.Requests[i].Name {
				v.Requests[i], v.Requests[j] = v.Requests[j], v.Requests[i]
			}
		}
	}

	want, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	want = append(want, '\n')
	if *update {
		if err := os.WriteFile("testdata/vectors.json", want, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	got, err := os.ReadFile("testdata/vectors.json")
	if err != nil || !bytes.Equal(got, want) {
		t.Fatalf("testdata/vectors.json is stale or missing (%v): run go test -run TestVectors -update . and rerun the TypeScript tests", err)
	}
}

func mustEventSpec() engine.RoundSpec {
	spec, err := testEvent().spec(deployed())
	if err != nil {
		panic(err)
	}
	return spec
}
